- name: Elastic repos on Deb
  when: ansible_facts.os_family == "Debian"
  block:
    - name: Add Elastic GPG key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: 'elastic-8.x'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Filebeat
      ansible.builtin.apt:
        name: filebeat
        state: present

- name: Elastic repos on Redhat
  when: ansible_facts.os_family == "RedHat"
  block:
    - name: Add Elastic Yum repository
      ansible.builtin.yum_repository:
        name: elastic-8.x
        description: Elastic repository for 8.x packages
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: yes

    - name: Install Filebeat
      ansible.builtin.yum:
        name: filebeat
        state: present

- name: Copy Filebeat conf
  template:
    src: filebeat.yml.j2
    dest: "{{ filebeat_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart filebeat

- name: Enable Filebeat mods
  shell: filebeat modules enable {{ item }}
  loop: "{{ filebeat_modules }}"
  notify: Restart filebeat

- name: Enable/start FB
  service:
    name: filebeat
    state: started
    enabled: true
