- name: Add right sources to fix snort install
  copy:
    content: "deb http://http.us.debian.org/debian/ bookworm non-free contrib main\n"
    dest: /etc/apt/sources.list.d/nonfree.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Snort
  package:
    name: snort
    state: present

- name: Configure minimal Snort configuration
  copy:
    content: "{{ snort_minimal_conf }}"
    dest: "{{ snort_conf_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart snort

- name: Ensure Snort is started and enabled
  service:
    name: snort
    state: started
    enabled: true
