- name: Check services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  register: service_check
  ignore_errors: yes
  loop: "{{ essential_services }}"

- name: Fail if any service is not running
  ansible.builtin.fail:
    msg: "{{ item.item }} not running"
  when: item.failed
  loop: "{{ service_check.results }}"
